service: png2jpg
frameworkVersion: '3'
provider:
  name: aws
  runtime: provided.al2
  stage: v1
  region: us-east-1
  architecture: x86_64

package:
  patterns:
    - '!./**'
    - bootstrap

functions:
  convert:
    handler: bootstrap
    events:
      - httpApi:
          path: /convert
          method: post
